apiVersion: v1
kind: Pod 
metadata:
  name: my-nginx
  labels: 
    app: nginx
    rel: stable
spec: 
  containers: 
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:

# kubectl create -f samples/pods/nginx.pod.yml --save-config
# k get pods
# k get pod my-nginx -o yaml
# kubectl apply -f samples/pods/nginx.pod.yml
# kubectl exec my-nginx -it sh
# # ls
# # cd usr
# # ls
# # cd share/nginx/html
# # ls
# # exit
# k edit -f samples/pods/nginx.pod.yml
# kubectl describe pod samples/pods/nginx.pod.yml
# kubectl describe pod [pod-name]
# kubectl apply -f nginx.pod.yml
# kubectl exec [pod-name] -it sh
# kubectl edit -f nginx.pod.yml